Make environment variables FILENAME and EVENT available
Hilzu/chokidar-cmd pull request #6
Opened 2017-01-28 00:55 UTC by thomasfl

Make the environment variables FILENAME and EVENT available for the supplied command. Makes it possible to only run jshint on the file that has changed:

```
  chokidar-cmd -c 'jshint $FILENAME' -t '**/*.js'
```

I got the idea for this feature when I wrote my similar command line utility in ruby https://github.com/thomasfl/filewatcher

2017-01-28 17:22 UTC, Hilzu requested changes

2017-01-28 17:22 UTC, Hilzu commented on cmd.js
> +    env.EVENT = event
I'd create a new object from `process.env` with `Object.assign({}, process.env, { FILENAME: path, EVENT: event})`. Modifying `process.env` directly also modifies the environment of the running process and I'd rather do that without a reason. As this package still supports node 0.12 the `Object.assign` function has to be imported from the `object-assign` package.

2017-01-28 17:22 UTC, Hilzu commented on README.md
> +     chokidar-cmd -c "jshint %FILENAME%" -t "**/*.js" Run jshint every time a js file changes on windows.
I'd add tests for the unix and windows environment variable injections

2017-01-28 17:28 UTC, Hilzu commented
I think this is a great addition to `chokidar-cmd`. Thank you for your PR!

2017-01-29 12:12 UTC, thomasfl commented on cmd.js
> +    env.EVENT = event
Ok. I've added the lates object-assign to package.json.

2017-01-29 12:14 UTC, thomasfl commented on README.md
> +     chokidar-cmd -c "jshint %FILENAME%" -t "**/*.js" Run jshint every time a js file changes on windows.
I do not have access to a windows machine and have only done manual tests.

2017-01-29 12:17 UTC, thomasfl commented
The environment variables have not been tested in an windows environment. Do not have access to a windows machine.

2017-01-30 14:46 UTC, Hilzu commented
AppVeyor runs the tests in Windows so if you create one for it will be run.

2017-01-30 14:47 UTC, Hilzu commented on cmd.js
> +    var env = objectAssign({}, process.env, {FILENAME: path, EVENT: event})
👍🏻

2017-01-30 14:48 UTC, Hilzu commented on cmd.js
> +const objectAssign = require('object-assign');
`const` isn't supported in node 0.12 and the semicolon is against standard code style

2018-02-03 20:59 UTC, closed without merging